# Generated by Django 4.0.4 on 2022-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_data_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
