# Generated by Django 4.0.4 on 2022-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
