version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Movies/:/usr/src/Movies/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - afd20a6efe451a16c541fd987b969de47ec6ba8fd8f135d27196f2af53ff4761:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db

volumes:
  afd20a6efe451a16c541fd987b969de47ec6ba8fd8f135d27196f2af53ff4761:
    external: True
    name: afd20a6efe451a16c541fd987b969de47ec6ba8fd8f135d27196f2af53ff4761



